# Generated by Django 3.2.23 on 2024-02-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviepostapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
